-- SIMPLE SQL QUERIES INSERTING VALUES FOR DEVELOPMENT --

-- CREATING SOME USERS --
INSERT INTO `users`(`username`, `password`, `email`) VALUES ("Dorian","password","email@email.com");
INSERT INTO `users`(`username`, `password`, `email`) VALUES ("test","password","test@email.com");
INSERT INTO `users`(`username`, `password`, `email`) VALUES ("test2","password","test2@email.com");

-- CREATING SOME BOARDS --
INSERT INTO `boards`(`name`, `description`) VALUES ("General","General description lorem ipsum");
INSERT INTO `boards`(`name`, `description`) VALUES ("Development","Development description lorem ipsum");
INSERT INTO `boards`(`name`, `description`) VALUES ("Smalltalk","Smalltalk description lorem ipsum");
INSERT INTO `boards`(`name`, `description`) VALUES ("Events","Events description lorem ipsum");

-- CREATING SOME TOPICS --
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Foodtruck", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idboards FROM `boards` WHERE name = "General"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Thé", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idboards FROM `boards` WHERE name = "General"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Machine a café", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idboards FROM `boards` WHERE name = "General"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("MYSQL ???", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idboards FROM `boards` WHERE name = "Development"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("PHP WTH ???", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idboards FROM `boards` WHERE name = "Development"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("WHAT IS CSS u know SASS BRO ???", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idboards FROM `boards` WHERE name = "Development"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Do you know da wae ?", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idboards FROM `boards` WHERE name = "Smalltalk"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Are you mad bruh?", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idboards FROM `boards` WHERE name = "Smalltalk"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Its chill outside...", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idboards FROM `boards` WHERE name = "Smalltalk"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Citizen of Wallonia", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idboards FROM `boards` WHERE name = "Events"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("Hack in the woods", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idboards FROM `boards` WHERE name = "Events"));
INSERT INTO `topics`(`title`, `creation_date`, `users_idusers`, `boards_idboards`) VALUES ("FOSDEM", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idboards FROM `boards` WHERE name = "Events"));

-- CREATING SOME MESSAGES --
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Foodtruck"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Foodtruck"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Foodtruck"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Foodtruck"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Thé"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Thé"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Thé"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Thé"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Machine a café"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Machine a café"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Machine a café"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Machine a café"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "MYSQL ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "MYSQL ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "MYSQL ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "MYSQL ???"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "PHP WTH ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "PHP WTH ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "PHP WTH ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "PHP WTH ???"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "WHAT IS CSS u know SASS BRO ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "WHAT IS CSS u know SASS BRO ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "WHAT IS CSS u know SASS BRO ???"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "WHAT IS CSS u know SASS BRO ???"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Do you know da wae ?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Do you know da wae ?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Do you know da wae ?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Do you know da wae ?"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Are you mad bruh?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Are you mad bruh?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Are you mad bruh?"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Are you mad bruh?"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Its chill outside..."));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Its chill outside..."));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Its chill outside..."));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Its chill outside..."));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Citizen of Wallonia"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Citizen of Wallonia"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Citizen of Wallonia"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Citizen of Wallonia"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Hack in the woods"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "Hack in the woods"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "Hack in the woods"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "Hack in the woods"));

INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur felis nulla, lacinia vel interdum non, rhoncus vitae est.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "FOSDEM"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Quisque ut placerat erat. Cras sollicitudin molestie elit id efficitur. Proin malesuada metus et lectus lobortis, in aliquam eros pharetra.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test"), (SELECT idtopics FROM `topics` WHERE title = "FOSDEM"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Maecenas sagittis nibh quis dictum dapibus.", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "Dorian"), (SELECT idtopics FROM `topics` WHERE title = "FOSDEM"));
INSERT INTO `messages`(`content`, `creation_date`, `users_idusers`, `topics_idtopics`) VALUES ("Nullam dignissim vel libero sed malesuada", CURRENT_TIMESTAMP, (SELECT idusers FROM `users` WHERE username = "test2"), (SELECT idtopics FROM `topics` WHERE title = "FOSDEM"));


